initial_exercises = [
    # Chest
    {
        "name": "Flat Barbell Bench Press",
        "category": "Chest",
        "specific_target": "General / Middle Chest",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Flat Dumbbell Bench Press",
        "category": "Chest",
        "specific_target": "General / Middle Chest",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Machine Chest Press",
        "category": "Chest",
        "specific_target": "General / Middle Chest",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Incline Dumbbell Press",
        "category": "Chest",
        "specific_target": "Upper Chest",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Incline Barbell Press",
        "category": "Chest",
        "specific_target": "Upper Chest",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Cable Chest Fly",
        "category": "Chest",
        "specific_target": "Inner Chest / Squeeze",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Pec Deck Machine",
        "category": "Chest",
        "specific_target": "Inner Chest / Squeeze",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    # Back
    {
        "name": "Pull-Up (Wide Grip)",
        "category": "Back",
        "specific_target": "Lats (Width)",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    {
        "name": "Lat Pulldown",
        "category": "Back",
        "specific_target": "Lats (Width)",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    {
        "name": "Single-Arm Lat Pulldown",
        "category": "Back",
        "specific_target": "Lats (Width)",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    {
        "name": "Bent-Over Barbell Row",
        "category": "Back",
        "specific_target": "Mid-Back (Thickness)",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    {
        "name": "Seated Cable Row",
        "category": "Back",
        "specific_target": "Mid-Back (Thickness)",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    {
        "name": "Single-Arm Dumbbell Row",
        "category": "Back",
        "specific_target": "Mid-Back (Thickness)",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    # Shoulders
    {
        "name": "Overhead Press (Barbell)",
        "category": "Shoulders",
        "specific_target": "Front / Whole Delt",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Seated Dumbbell Press",
        "category": "Shoulders",
        "specific_target": "Front / Whole Delt",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Machine Shoulder Press",
        "category": "Shoulders",
        "specific_target": "Front / Whole Delt",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    {
        "name": "Dumbbell Lateral Raise",
        "category": "Shoulders",
        "specific_target": "Side Delt",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Cable Lateral Raise",
        "category": "Shoulders",
        "specific_target": "Side Delt",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Face Pull",
        "category": "Shoulders",
        "specific_target": "Rear Delt",
        "exercise_type": "Pull",
        "mechanics": "Compound",
    },
    {
        "name": "Reverse Pec Deck",
        "category": "Shoulders",
        "specific_target": "Rear Delt",
        "exercise_type": "Pull",
        "mechanics": "Isolation",
    },
    # Legs
    {
        "name": "Barbell Back Squat",
        "category": "Legs",
        "specific_target": "Quads",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Leg Press",
        "category": "Legs",
        "specific_target": "Quads",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Goblet Squat",
        "category": "Legs",
        "specific_target": "Quads",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Leg Extension",
        "category": "Legs",
        "specific_target": "Quads (Isolation)",
        "exercise_type": "Legs (Push)",
        "mechanics": "Isolation",
    },
    {
        "name": "Bulgarian Split Squat",
        "category": "Legs",
        "specific_target": "Quads (Unilateral)",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Walking Lunges",
        "category": "Legs",
        "specific_target": "Quads (Unilateral)",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Romanian Deadlift (RDL)",
        "category": "Legs",
        "specific_target": "Hamstrings",
        "exercise_type": "Legs (Pull)",
        "mechanics": "Compound",
    },
    {
        "name": "Lying Leg Curl",
        "category": "Legs",
        "specific_target": "Hamstrings",
        "exercise_type": "Legs (Pull)",
        "mechanics": "Isolation",
    },
    {
        "name": "Seated Leg Curl",
        "category": "Legs",
        "specific_target": "Hamstrings",
        "exercise_type": "Legs (Pull)",
        "mechanics": "Isolation",
    },
    {
        "name": "Barbell Hip Thrust",
        "category": "Legs",
        "specific_target": "Glutes",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Glute Bridge",
        "category": "Legs",
        "specific_target": "Glutes",
        "exercise_type": "Legs (Push)",
        "mechanics": "Compound",
    },
    {
        "name": "Cable Pull-Through",
        "category": "Legs",
        "specific_target": "Glutes",
        "exercise_type": "Legs (Pull)",
        "mechanics": "Compound",
    },
    # Triceps
    {
        "name": "Tricep Rope Pushdown",
        "category": "Triceps",
        "specific_target": "General Triceps",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Straight Bar Pushdown",
        "category": "Triceps",
        "specific_target": "General Triceps",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Overhead Dumbbell Extension",
        "category": "Triceps",
        "specific_target": "Long Head (Overhead)",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Skullcrusher (EZ Bar)",
        "category": "Triceps",
        "specific_target": "Long Head (Overhead)",
        "exercise_type": "Push",
        "mechanics": "Isolation",
    },
    {
        "name": "Dips (Upright)",
        "category": "Triceps",
        "specific_target": "Compound / Lower",
        "exercise_type": "Push",
        "mechanics": "Compound",
    },
    # Biceps
    {
        "name": "Barbell Bicep Curl",
        "category": "Biceps",
        "specific_target": "General Biceps",
        "exercise_type": "Pull",
        "mechanics": "Isolation",
    },
    {
        "name": "Dumbbell Bicep Curl",
        "category": "Biceps",
        "specific_target": "General Biceps",
        "exercise_type": "Pull",
        "mechanics": "Isolation",
    },
    {
        "name": "Cable Bicep Curl",
        "category": "Biceps",
        "specific_target": "General Biceps",
        "exercise_type": "Pull",
        "mechanics": "Isolation",
    },
    {
        "name": "Dumbbell Hammer Curl",
        "category": "Biceps",
        "specific_target": "Brachialis / Forearm",
        "exercise_type": "Pull",
        "mechanics": "Isolation",
    },
    {
        "name": "Rope Cable Hammer Curl",
        "category": "Biceps",
        "specific_target": "Brachialis / Forearm",
        "exercise_type": "Pull",
        "mechanics": "Isolation",
    },
    # Core
    {
        "name": "Hanging Leg Raise",
        "category": "Core",
        "specific_target": "Lower Abs",
        "exercise_type": "Core",
        "mechanics": "Isolation",
    },
    {
        "name": "Captain's Chair Leg Raise",
        "category": "Core",
        "specific_target": "Lower Abs",
        "exercise_type": "Core",
        "mechanics": "Isolation",
    },
    {
        "name": "Cable Crunch",
        "category": "Core",
        "specific_target": "Upper Abs",
        "exercise_type": "Core",
        "mechanics": "Isolation",
    },
    {
        "name": "Machine Crunch",
        "category": "Core",
        "specific_target": "Upper Abs",
        "exercise_type": "Core",
        "mechanics": "Isolation",
    },
    {
        "name": "Cable Woodchopper",
        "category": "Core",
        "specific_target": "Obliques",
        "exercise_type": "Core",
        "mechanics": "Compound",
    },
    {
        "name": "Russian Twist",
        "category": "Core",
        "specific_target": "Obliques",
        "exercise_type": "Core",
        "mechanics": "Isolation",
    },
]

